#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.MSP430{1,0,4.0,0
#
main.x430: package/cfg/main.x430.mak

clean::
	-$(RM) package/cfg/main.x430.mak
